# Generated by Django 4.2.5 on 2023-10-11 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="category")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="phone number")),
                (
                    "address1",
                    models.CharField(
                        default="", max_length=200, verbose_name="address"
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        default="", max_length=200, verbose_name="address"
                    ),
                ),
                (
                    "city",
                    models.CharField(default="", max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(default="", max_length=100, verbose_name="state"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        default="", max_length=100, verbose_name="zip code"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer",
                "verbose_name_plural": "customers",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="product name"),
                ),
                ("price", models.IntegerField(default=0, verbose_name="product price")),
                ("desc", models.CharField(max_length=300, verbose_name="description")),
                (
                    "image",
                    models.ImageField(upload_to="images/images", verbose_name="image"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myShop.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="order id"
                    ),
                ),
                (
                    "items_json",
                    models.CharField(max_length=5000, verbose_name="order items"),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="quantity")),
                (
                    "oid",
                    models.CharField(blank=True, max_length=150, verbose_name="oid"),
                ),
                (
                    "amountpaid",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "paymentstatus",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="payment status"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myShop.customer",
                        verbose_name="customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "order",
                "verbose_name_plural": "orders",
            },
        ),
    ]
